FROM golang:1.24

# WORKDIR /opt/user
# WORKDIR /opt/codes/hello

# COPY hello.go .

# RUN go build -o hello hello.go

# CMD ["./hello"]
# CMD ["go", "version"]

# 保持容器运行
CMD ["tail", "-f", "/dev/null"]
